#!/usr/bin/env python3
"""Build a daily cross-channel report from email and WhatsApp summaries."""

from __future__ import annotations

import argparse
import csv
import holidays
import shutil
import sys
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta
from pathlib import Path
import re


CHAT_ENTRY_RE = re.compile(
    r"^\[(\d{2}/\d{2}/\d{2}), (\d{2}:\d{2}:\d{2})\] ([^:]+):\s?(.*)$"
)
FRENCH_HOLIDAYS = holidays.FR()
SUMMARY_FIELDNAMES = [
    "type",
    "timestamp",
    "From address",
    "from name",
    "To address",
    "To name",
    "file",
]


@dataclass(frozen=True)
class SentMessage:
    source: str
    timestamp: datetime
    recipient_name: str
    recipient_address: str
    file_path: Path
    summary_row: dict[str, str]


@dataclass(frozen=True)
class ChatEntry:
    message_dt: datetime
    sender_name: str
    raw_text: str


class ProgressReporter:
    def __init__(self, total_days: int, enabled: bool) -> None:
        self.total_days = max(total_days, 1)
        self.enabled = enabled
        self.is_tty = enabled and sys.stdout.isatty()
        self.last_render = ""
        self.last_plain_percent = -1

    def update(self, processed_days: int) -> None:
        if not self.enabled:
            return

        percent = min(100.0, (processed_days / self.total_days) * 100.0)
        line = f"{percent:6.2f}% | processed {processed_days}/{self.total_days} days"

        if self.is_tty:
            padding = ""
            if len(self.last_render) > len(line):
                padding = " " * (len(self.last_render) - len(line))
            sys.stdout.write(f"\r{line}{padding}")
            sys.stdout.flush()
            self.last_render = line
            return

        rounded = int(percent)
        if rounded != self.last_plain_percent:
            print(line, flush=True)
            self.last_plain_percent = rounded

    def finish(self) -> None:
        if self.enabled and self.is_tty and self.last_render:
            sys.stdout.write("\n")
            sys.stdout.flush()
            self.last_render = ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a daily cross-channel report from email and WhatsApp summaries."
    )
    parser.add_argument(
        "--email-summary",
        required=True,
        help="Path to the email summary CSV generated by extract_mbox_messages.py.",
    )
    parser.add_argument(
        "--whatsapp-summary",
        required=True,
        help="Path to the WhatsApp summary CSV generated by extract_whatsapp_messages.py.",
    )
    parser.add_argument(
        "--start-date",
        required=True,
        help="Inclusive start date in YYYY-MM-DD format.",
    )
    parser.add_argument(
        "--end-date",
        required=True,
        help="Inclusive end date in YYYY-MM-DD format.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory where the daily report artifacts are written.",
    )
    parser.add_argument(
        "--no-progress",
        action="store_true",
        help="Disable progress reporting.",
    )
    return parser.parse_args()


def parse_cli_date(value: str, label: str) -> date:
    try:
        return datetime.strptime(value, "%Y-%m-%d").date()
    except ValueError as exc:
        raise ValueError(f"Invalid {label} '{value}'. Expected YYYY-MM-DD.") from exc


def parse_timestamp_local(timestamp_text: str) -> datetime:
    parsed = datetime.fromisoformat(timestamp_text)
    if parsed.tzinfo is not None:
        parsed = parsed.replace(tzinfo=None)
    return parsed


def parse_chat_datetime(date_text: str, time_text: str) -> datetime:
    return datetime.strptime(f"{date_text}, {time_text}", "%d/%m/%y, %H:%M:%S")


def parse_chat_entries(text: str) -> list[ChatEntry]:
    entries: list[ChatEntry] = []
    current_entry: ChatEntry | None = None

    for line in text.splitlines(keepends=True):
        match = CHAT_ENTRY_RE.match(line)
        if match:
            try:
                message_dt = parse_chat_datetime(match.group(1), match.group(2))
            except ValueError:
                current_entry = None
                continue

            current_entry = ChatEntry(
                message_dt=message_dt,
                sender_name=match.group(3).strip(),
                raw_text=line,
            )
            entries.append(current_entry)
            continue

        if line.startswith("["):
            current_entry = None
            continue

        if current_entry is not None:
            updated_entry = ChatEntry(
                message_dt=current_entry.message_dt,
                sender_name=current_entry.sender_name,
                raw_text=current_entry.raw_text + line,
            )
            entries[-1] = updated_entry
            current_entry = updated_entry

    return entries


def read_summary(summary_path: Path, expected_type: str) -> list[SentMessage]:
    messages: list[SentMessage] = []
    with summary_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            if row.get("type") != expected_type:
                continue

            timestamp_text = (row.get("timestamp") or "").strip()
            file_text = (row.get("file") or "").strip()
            if not timestamp_text or not file_text:
                continue

            timestamp = parse_timestamp_local(timestamp_text)
            file_path = (summary_path.parent / Path(file_text)).resolve()
            messages.append(
                SentMessage(
                    source=expected_type,
                    timestamp=timestamp,
                    recipient_name=(row.get("To name") or "").strip(),
                    recipient_address=(row.get("To address") or "").strip(),
                    file_path=file_path,
                    summary_row={field: row.get(field, "") for field in SUMMARY_FIELDNAMES},
                )
            )

    messages.sort(key=lambda message: (message.timestamp, message.source, message.file_path.as_posix()))
    return messages


def iter_dates(start_date: date, end_date: date):
    current = start_date
    one_day = timedelta(days=1)
    while current <= end_date:
        yield current
        current += one_day


def compute_boundary_for_date(target_date: date, sent_messages: list[SentMessage]) -> datetime:
    window_start = datetime.combine(target_date, time(0, 0, 0))
    window_end = datetime.combine(target_date, time(10, 0, 0))
    window_messages = [
        message.timestamp
        for message in sent_messages
        if window_start <= message.timestamp <= window_end
    ]

    if not window_messages:
        return window_end

    gaps: list[tuple[timedelta, datetime]] = []
    gaps.append((window_messages[0] - window_start, window_messages[0]))

    for previous, current in zip(window_messages, window_messages[1:]):
        gaps.append((current - previous, current))

    gaps.append((window_end - window_messages[-1], window_end))
    return max(gaps, key=lambda item: (item[0], item[1]))[1]


def build_boundaries(
    start_date: date,
    end_date: date,
    sent_messages: list[SentMessage],
) -> dict[date, datetime]:
    boundaries: dict[date, datetime] = {}
    for current_date in iter_dates(start_date, end_date + timedelta(days=1)):
        boundaries[current_date] = compute_boundary_for_date(current_date, sent_messages)
    return boundaries


def assign_messages_to_days(
    start_date: date,
    end_date: date,
    sent_messages: list[SentMessage],
    boundaries: dict[date, datetime],
) -> dict[date, list[SentMessage]]:
    by_day = {current_date: [] for current_date in iter_dates(start_date, end_date)}
    for current_date in iter_dates(start_date, end_date):
        start_boundary = boundaries[current_date]
        end_boundary = boundaries[current_date + timedelta(days=1)]
        by_day[current_date] = [
            message
            for message in sent_messages
            if start_boundary <= message.timestamp < end_boundary
        ]
    return by_day


def ensure_unique_path(destination_dir: Path, filename: str) -> Path:
    candidate = destination_dir / filename
    suffix = 1
    while candidate.exists():
        stem = Path(filename).stem
        extension = Path(filename).suffix
        candidate = destination_dir / f"{stem}_{suffix}{extension}"
        suffix += 1
    return candidate


def export_email_messages(day_dir: Path, messages: list[SentMessage]) -> None:
    email_dir = day_dir / "email"
    email_dir.mkdir(parents=True, exist_ok=True)
    for message in messages:
        destination = ensure_unique_path(email_dir, message.file_path.name)
        shutil.copy2(message.file_path, destination)


def export_whatsapp_messages(day_dir: Path, messages: list[SentMessage]) -> None:
    whatsapp_dir = day_dir / "whatsapp"
    whatsapp_dir.mkdir(parents=True, exist_ok=True)

    messages_by_chat: dict[Path, list[SentMessage]] = {}
    for message in messages:
        messages_by_chat.setdefault(message.file_path, []).append(message)

    for chat_path, chat_messages in messages_by_chat.items():
        chat_messages.sort(key=lambda message: message.timestamp)
        first_sent = chat_messages[0].timestamp - timedelta(hours=1)
        last_sent = chat_messages[-1].timestamp + timedelta(hours=1)

        chat_text = chat_path.read_text(encoding="utf-8")
        entries = parse_chat_entries(chat_text)
        exported = [
            entry.raw_text
            for entry in entries
            if first_sent <= entry.message_dt <= last_sent
        ]

        destination = ensure_unique_path(whatsapp_dir, chat_path.name)
        destination.write_text("".join(exported), encoding="utf-8", newline="")


def format_time_or_empty(value: datetime | None) -> str:
    if value is None:
        return ""
    return value.strftime("%H:%M:%S")


def classify_day_type(day_date: date) -> str:
    holiday_name = FRENCH_HOLIDAYS.get(day_date)
    if holiday_name:
        holiday_label = str(holiday_name).strip()
        if holiday_label:
            return f"public holiday: {holiday_label}"
        return "public holiday"

    if day_date in FRENCH_HOLIDAYS:
        return "public holiday"

    if day_date.weekday() >= 5:
        return "weekend"

    return "working"


def compute_working_start(
    day_date: date,
    first_message: SentMessage | None,
    non_working_day: bool,
) -> str:
    if non_working_day:
        return format_time_or_empty(first_message.timestamp if first_message else None)

    threshold = time(10, 0, 0)
    if first_message is None or first_message.timestamp.time() >= threshold:
        return "10:00:00"
    return first_message.timestamp.strftime("%H:%M:%S")


def compute_working_end(
    day_date: date,
    last_message: SentMessage | None,
    non_working_day: bool,
) -> str:
    if non_working_day:
        return format_time_or_empty(last_message.timestamp if last_message else None)

    threshold = datetime.combine(day_date, time(19, 0, 0))
    if last_message is None or last_message.timestamp <= threshold:
        return "19:00:00"
    return last_message.timestamp.strftime("%H:%M:%S")


def has_lunch_message(messages: list[SentMessage]) -> bool:
    lunch_start = time(12, 0, 0)
    lunch_end = time(14, 0, 0)
    return any(lunch_start <= message.timestamp.time() <= lunch_end for message in messages)


def build_day_summary_row(day_date: date, messages: list[SentMessage]) -> dict[str, str]:
    first_message = messages[0] if messages else None
    last_message = messages[-1] if messages else None
    day_type = classify_day_type(day_date)
    non_working_day = day_type != "working"
    return {
        "date": day_date.isoformat(),
        "day type": day_type,
        "first message time": format_time_or_empty(first_message.timestamp if first_message else None),
        "first message recipent name": first_message.recipient_name if first_message else "",
        "first message recipient address": first_message.recipient_address if first_message else "",
        "last message time": format_time_or_empty(last_message.timestamp if last_message else None),
        "last message recipent name": last_message.recipient_name if last_message else "",
        "last message recipient address": last_message.recipient_address if last_message else "",
        "messages in lunch time": "YES" if has_lunch_message(messages) else "NO",
        "start working time": compute_working_start(day_date, first_message, non_working_day),
        "end working time": compute_working_end(day_date, last_message, non_working_day),
    }


def write_day_summary(output_dir: Path, rows: list[dict[str, str]]) -> None:
    summary_path = output_dir / "by_day.csv"
    fieldnames = [
        "date",
        "day type",
        "first message time",
        "first message recipent name",
        "first message recipient address",
        "last message time",
        "last message recipent name",
        "last message recipient address",
        "messages in lunch time",
        "start working time",
        "end working time",
    ]
    with summary_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_day_message_summary(day_dir: Path, messages: list[SentMessage]) -> None:
    summary_path = day_dir / "day_summary.csv"
    rows = [
        message.summary_row
        for message in sorted(
            messages,
            key=lambda message: (
                message.timestamp,
                message.source,
                message.summary_row.get("file", ""),
            ),
        )
    ]
    with summary_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=SUMMARY_FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    args = parse_args()

    email_summary = Path(args.email_summary)
    whatsapp_summary = Path(args.whatsapp_summary)
    if not email_summary.is_file():
        print(f"Email summary not found: {email_summary}", file=sys.stderr)
        return 1
    if not whatsapp_summary.is_file():
        print(f"WhatsApp summary not found: {whatsapp_summary}", file=sys.stderr)
        return 1

    try:
        start_date = parse_cli_date(args.start_date, "start date")
        end_date = parse_cli_date(args.end_date, "end date")
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    if start_date > end_date:
        print("Start date must be less than or equal to end date.", file=sys.stderr)
        return 1

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        email_messages = read_summary(email_summary, "email")
        whatsapp_messages = read_summary(whatsapp_summary, "whatsapp")
    except (OSError, ValueError) as exc:
        print(f"Failed to read summaries: {exc}", file=sys.stderr)
        return 1

    sent_messages = sorted(
        email_messages + whatsapp_messages,
        key=lambda message: (message.timestamp, message.source, message.file_path.as_posix()),
    )

    boundaries = build_boundaries(start_date, end_date, sent_messages)
    assigned_messages = assign_messages_to_days(start_date, end_date, sent_messages, boundaries)
    total_days = (end_date - start_date).days + 1
    reporter = ProgressReporter(total_days=total_days, enabled=not args.no_progress)

    summary_rows: list[dict[str, str]] = []
    processed_days = 0
    try:
        for current_date in iter_dates(start_date, end_date):
            day_messages = assigned_messages[current_date]
            summary_rows.append(build_day_summary_row(current_date, day_messages))

            if day_messages:
                day_dir = (
                    output_dir
                    / current_date.strftime("%Y")
                    / current_date.strftime("%m")
                    / current_date.strftime("%d")
                )
                email_day_messages = [message for message in day_messages if message.source == "email"]
                whatsapp_day_messages = [message for message in day_messages if message.source == "whatsapp"]

                if email_day_messages:
                    export_email_messages(day_dir, email_day_messages)
                if whatsapp_day_messages:
                    export_whatsapp_messages(day_dir, whatsapp_day_messages)

                write_day_message_summary(day_dir, day_messages)

            processed_days += 1
            reporter.update(processed_days=processed_days)
    finally:
        reporter.finish()

    write_day_summary(output_dir, summary_rows)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
