#!/usr/bin/env python3
"""Fill an existing XLSX workbook from a by_day.csv summary."""

from __future__ import annotations

import argparse
import csv
import re
import sys
from dataclasses import dataclass
from datetime import date, datetime, time
from pathlib import Path

try:
    from openpyxl import load_workbook
except ModuleNotFoundError as exc:  # pragma: no cover - depends on local environment
    missing_dependency_error = exc
    load_workbook = None
else:
    missing_dependency_error = None


REQUIRED_HEADERS = {
    "date",
    "day type",
    "messages in lunch time",
    "start working time",
    "end working time",
}
DATE_CELL_RE = re.compile(r"^\s*(\d{1,2})/(\d{1,2})/(\d{4})\s*$")
TIME_FORMAT = "%H:%M:%S"
LUNCH_START_MINUTES = 12 * 60
LUNCH_END_MINUTES = 14 * 60


@dataclass(frozen=True)
class DaySummary:
    day: date
    day_type: str
    lunch_flag: str
    start_time: time | None
    end_time: time | None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fill start/end/lunch cells in an XLSX workbook from by_day.csv."
    )
    parser.add_argument(
        "--input-file",
        required=True,
        help="Path to the by_day.csv file generated by build_daily_report.py.",
    )
    parser.add_argument(
        "--excel-file",
        required=True,
        help="Path to the XLSX workbook to edit in place.",
    )
    parser.add_argument(
        "--date-column",
        required=True,
        help="Column letter containing dates in d/m/yyyy or dd/mm/yyyy format.",
    )
    parser.add_argument(
        "--start-working-column",
        required=True,
        help="Column letter where the start working hour will be written.",
    )
    parser.add_argument(
        "--end-working-column",
        required=True,
        help="Column letter where the end working hour will be written.",
    )
    parser.add_argument(
        "--lunch-break-column",
        required=True,
        help="Column letter where the lunch break hours will be written.",
    )
    return parser.parse_args()


def normalize_column_letter(value: str, label: str) -> str:
    normalized = value.strip().upper()
    if not normalized or not normalized.isalpha():
        raise ValueError(f"Invalid {label} '{value}'. Expected an Excel column letter.")
    return normalized


def parse_csv_date(value: str) -> date:
    try:
        return datetime.strptime(value.strip(), "%Y-%m-%d").date()
    except ValueError as exc:
        raise ValueError(f"Invalid CSV date '{value}'. Expected YYYY-MM-DD.") from exc


def parse_sheet_date(value: object) -> date | None:
    if value is None:
        return None

    if isinstance(value, datetime):
        return value.date()

    if isinstance(value, date):
        return value

    text = str(value).strip()
    if not text:
        return None

    match = DATE_CELL_RE.match(text)
    if match is None:
        return None

    day_text, month_text, year_text = match.groups()
    try:
        return date(int(year_text), int(month_text), int(day_text))
    except ValueError:
        return None


def parse_optional_time(value: str, day_value: date, field_label: str) -> time | None:
    text = value.strip()
    if not text:
        return None

    try:
        return datetime.strptime(text, TIME_FORMAT).time()
    except ValueError as exc:
        raise ValueError(
            f"Invalid {field_label} '{value}' for CSV date {day_value.isoformat()}. "
            "Expected HH:MM:SS or blank."
        ) from exc


def load_day_summaries(csv_path: Path) -> dict[date, DaySummary]:
    try:
        with csv_path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            fieldnames = set(reader.fieldnames or [])
            missing_headers = REQUIRED_HEADERS - fieldnames
            if missing_headers:
                missing_list = ", ".join(sorted(missing_headers))
                raise ValueError(f"Missing required CSV header(s): {missing_list}")

            summaries: dict[date, DaySummary] = {}
            for row in reader:
                day_value = parse_csv_date(row["date"])
                if day_value in summaries:
                    raise ValueError(
                        f"Duplicate CSV date '{day_value.isoformat()}' found in {csv_path}."
                    )

                lunch_flag = (row["messages in lunch time"] or "").strip().upper()
                if lunch_flag and lunch_flag not in {"YES", "NO"}:
                    raise ValueError(
                        "Invalid lunch flag "
                        f"'{row['messages in lunch time']}' for CSV date {day_value.isoformat()}."
                    )

                summaries[day_value] = DaySummary(
                    day=day_value,
                    day_type=(row["day type"] or "").strip().lower(),
                    lunch_flag=lunch_flag,
                    start_time=parse_optional_time(
                        row["start working time"],
                        day_value,
                        "start working time",
                    ),
                    end_time=parse_optional_time(
                        row["end working time"],
                        day_value,
                        "end working time",
                    ),
                )

            return summaries
    except OSError as exc:
        raise OSError(f"Failed to read input CSV '{csv_path}': {exc}") from exc


def time_to_minutes(time_value: time) -> int:
    return (time_value.hour * 60) + time_value.minute


def interval_crosses_lunch(start_time: time, end_time: time) -> bool:
    start_minutes = time_to_minutes(start_time)
    end_minutes = time_to_minutes(end_time)
    if end_minutes < start_minutes:
        end_minutes += 24 * 60

    return not (
        end_minutes < LUNCH_START_MINUTES or start_minutes > LUNCH_END_MINUTES
    )


def time_to_excel_decimal(time_value: time, *, add_24_hours: bool = False) -> float:
    hour_value = time_value.hour + (24 if add_24_hours else 0)
    return float(f"{hour_value}.{time_value.minute:02d}")


def update_workbook(
    excel_path: Path,
    summaries: dict[date, DaySummary],
    *,
    date_column: str,
    start_column: str,
    end_column: str,
    lunch_column: str,
) -> None:
    try:
        workbook = load_workbook(excel_path)
    except OSError as exc:
        raise OSError(f"Failed to open Excel file '{excel_path}': {exc}") from exc
    except Exception as exc:
        raise ValueError(f"Failed to load Excel workbook '{excel_path}': {exc}") from exc

    if len(workbook.worksheets) != 1:
        raise ValueError(
            f"Expected exactly one worksheet in '{excel_path}', found {len(workbook.worksheets)}."
        )

    sheet = workbook.worksheets[0]

    for row_index in range(1, sheet.max_row + 1):
        row_date = parse_sheet_date(sheet[f"{date_column}{row_index}"].value)
        if row_date is None:
            continue

        summary = summaries.get(row_date)
        if summary is None:
            continue

        if (
            summary.start_time is not None
            and summary.end_time is not None
            and summary.start_time == summary.end_time
        ):
            continue

        wrote_start = False
        wrote_end = False

        if summary.start_time is not None:
            sheet[f"{start_column}{row_index}"] = time_to_excel_decimal(summary.start_time)
            wrote_start = True

        if summary.end_time is not None:
            add_24_hours = (
                summary.start_time is not None and summary.end_time < summary.start_time
            )
            sheet[f"{end_column}{row_index}"] = time_to_excel_decimal(
                summary.end_time,
                add_24_hours=add_24_hours,
            )
            wrote_end = True

        if wrote_start and wrote_end:
            if summary.lunch_flag not in {"YES", "NO"}:
                raise ValueError(
                    f"Invalid lunch flag '{summary.lunch_flag}' for CSV date {row_date.isoformat()}."
                )
            if (
                summary.day_type != "working"
                and summary.start_time is not None
                and summary.end_time is not None
                and not interval_crosses_lunch(summary.start_time, summary.end_time)
            ):
                continue

            sheet[f"{lunch_column}{row_index}"] = 1.0 if summary.lunch_flag == "NO" else 0.0

    try:
        workbook.save(excel_path)
    except OSError as exc:
        raise OSError(f"Failed to save Excel file '{excel_path}': {exc}") from exc


def main() -> int:
    if missing_dependency_error is not None:
        print(
            "Missing dependency: openpyxl. Install it in the virtualenv before running this script.",
            file=sys.stderr,
        )
        return 1

    args = parse_args()

    input_file = Path(args.input_file)
    excel_file = Path(args.excel_file)

    if not input_file.is_file():
        print(f"Input file not found: {input_file}", file=sys.stderr)
        return 1

    if not excel_file.is_file():
        print(f"Excel file not found: {excel_file}", file=sys.stderr)
        return 1

    try:
        date_column = normalize_column_letter(args.date_column, "date column")
        start_column = normalize_column_letter(
            args.start_working_column,
            "start working column",
        )
        end_column = normalize_column_letter(
            args.end_working_column,
            "end working column",
        )
        lunch_column = normalize_column_letter(
            args.lunch_break_column,
            "lunch break column",
        )
        summaries = load_day_summaries(input_file)
        update_workbook(
            excel_file,
            summaries,
            date_column=date_column,
            start_column=start_column,
            end_column=end_column,
            lunch_column=lunch_column,
        )
    except (OSError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
